######################################################################
# Automatically generated by qmake (3.0) mar. avr. 3 16:55:37 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = tp7
INCLUDEPATH += .

# Input
HEADERS += mainwindow.hpp
SOURCES += main.cpp mainwindow.cpp
