######################################################################
# Automatically generated by qmake (3.0) mar. avr. 3 17:38:32 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = tp8
INCLUDEPATH += .

# Input
HEADERS += fenetrePrincipale.hpp MyScene.hpp
SOURCES += fenetrePrincipale.cpp main.cpp MyScene.cpp
