######################################################################
# Automatically generated by qmake (3.0) sam. mai 5 15:29:39 2018
######################################################################

QT += widgets
TEMPLATE = app
TARGET = miniprojetCPP
INCLUDEPATH += .

# Input
HEADERS += Animal.hpp mainWindow.hpp Scene.hpp World.hpp
SOURCES += Animal.cpp main.cpp mainWindow.cpp Scene.cpp World.cpp
